# test_config.yaml
# Single trial test run using Prospect 1 data

simulation:
  type: 'Single Trial'
  dt: 0.05
  max_runtime: 120
  iterations_per_trial: 1

  recovery_sim: true
  launch_rail_length: 5.0
  launchrail_orientation: [0, 0, 1]

rocket:
  ORK_path: 'user_inputs/rocket_data/'
  ORK_filename: 'p1ORK-6dof.csv'

  RasAero_path: 'user_inputs/rocket_data/'
  RasAero_filename: 'p1ras-6dof.csv'

  reference_area: 0.03242927866  # m^2

  #overrides:
  #  mass: 14.5          # constant total mass (kg)
  #  cg: 1.15            # constant CG from nose tip (m)
  #  thrust_scale: 1.0   # multiplier on thrust curve

recovery:
  CdA: [1.0, 10.0]
  deployment_altitude: [null, 500]

wind:
  type: simple
  magnitude: 3.0
  direction: 0.785   # radians CW from North, ~45 deg (NE)
  turbulence_intensity: 1.0
  alt_min: 0.0
  alt_max: 10000.0 # TODO: automate this
  alt_steps: 100

record:
  - apogee
  - max_velocity
  - flight_time
