# ============================
#  SAMPLE CONFIG FILE WEEEEE
# ============================

simulation:
  type: 'Trade'              # as opposed to 'Single Trial'
  #dof: '6DOF'              # as opposed to '1D'
  dt: 0.05                  # timestep (s)
  max_runtime: 200          # (s)
  iterations_per_trial: 10  # for differing environmental conditions per configuration

  recovery_sim: true
  launch_rail_length: 5.0
  launchrail_length: 13
  launchrail_orientation: [0, 0, 1] 

rocket:
  ORK_path: 'some/path/here/'
  ORK_filename: 'ProspectORK.csv'

	# include option for length interpolated rocket
  RasAero_path: 'another/one/'
  RasAero_filename: 'ProspectRas.csv'

  #OVERRIDE_mass: !linspace [8e4, 10e4, 10]


trade_study:
  blocks:
    - name: 'engine design'
      parameters:
        engine_mass: !linspace [20.0, 30.0, 10]
        thrust: !linspace [1000.0, 2000.0, 10]

    - name: 'fin sizing'
      parameters:
        height: !linspace [8.0, 16.0, 5]


recovery:
  parachute_count: 2
  CdA: [1, 2]
  deployment_altitude: [null, 2000]

environment:
	model: SEB-v1.0
  wind_shear_path: 'wind_data/'
  wind_shear_filename: 'wind.csv'

  OVERRIDE_gust_W20: 15

record:
  - apogee
  - max_velocity
  - flight_time

